version: '3.8'

services:
  frontend:
    image: okinteligenciaartificial/frontend:latest
    build:
      context: ./app
      dockerfile: dockerfile
    networks:
      - network_swarm_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`app.okinteligenciaartificial.com.br`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.frontend.loadbalancer.server.port=5000"
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  network_swarm_public:
    external: true
