
FROM debian:12

# Variaveis globais de ambiente
ENV \
    MAINTAINER="Rafael Pereira" \
    EMAIL=okinteligenciaartificial@gmail.com \
    TERM=xterm \
    SHELL=/bin/bash \
    TZ=America/Sao_Paulo \
    PS1='\u@\h:\w\$ ' \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8

# Atualiza os repositórios e pacotes
RUN ( \
    apt-get -y update        || apt-get -y update           || exit 10; \
    apt-get -y upgrade       || apt-get -y upgrade          || exit 11; \
    apt-get -y dist-upgrade  || apt-get -y dist-upgrade     || exit 12; \
    \
    apt-get -y install procps psutils coreutils util-linux  || exit 13; \
    apt-get -y install sed gpg curl git iproute2            || exit 14; \
)

# Python base
RUN ( \
    apt-get install -y python3            || exit 31; \
    apt-get install -y python3-numpy      || exit 32; \
    apt-get install -y python3-pip        || exit 33; \
    apt-get install -y python3-flask      || exit 34; \
    apt-get install -y python3-setuptools || exit 35; \
    apt-get install -y python3-setuptools-rust || exit 36; \
)

# Clean
RUN ( mkdir -p /app; rm -rf /var/lib/apt/lists/*; )

WORKDIR /app
COPY app.py       /app/

EXPOSE 5000
CMD ["python3", "app.py"]
